version: "3"
services:
  db:
    image: ubuntu/mysql:8.0-20.04_beta
    restart: always
    environment:
      MYSQL_DATABASE: 'reddifi'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql